image: alpine/edge
oauth: pages.sr.ht/PAGES:RW
packages:
  - nodejs
  - npm
  - hut
sources:
  - https://git.sr.ht/~kaytwolf/love-jar
secrets:
  - 7529e47d-69a6-43cd-8b1f-defe58fdef72
tasks:
  - install-pnpm: sudo npm i -g pnpm
  - setup: |
      cd love-jar
      pnpm i
  - build: |
      cd love-jar
      pnpm build
  - package: |
      cd love-jar/dist
      tar -cvz . > ../../love-jar.tar.gz
  - upload: |
      hut pages publish -d kaytwolf.srht.site -s love-jar love-jar.tar.gz
