image: alpine/edge
packages:
  - nodejs
  - npm
sources:
  - https://git.sr.ht/~kaytwolf/love-jar
secrets:
  - 7529e47d-69a6-43cd-8b1f-defe58fdef72
tasks:
  - install-pnpm: sudo npm i -g pnpm
  - setup: |
      cd love-jar
      pnpm i
  - build: |
      cd love-jar
      pnpm build
      touch dist/.nojekyll
  - deploy: |
      cd love-jar/dist
      git init
      git checkout -b main
      git add -A
      git config --global user.email "builds@ayxh.dev"
      git config --global user.name "Andrew Huang"
      git commit -m "deploy"
      git remote add origin git@github.com:AndrewYHuang/love-jar.git
      git push --force
