image: alpine/edge
packages:
  - nodejs
  - npm
sources:
  - https://git.sr.ht/~kaytwolf/love-jar
tasks:
  - install-pnpm: sudo npm i -g pnpm
  - setup: |
      cd love-jar
      pnpm i
  - build: |
      cd love-jar
      pnpm build
